// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package jp.springbook.springroosample.mydata;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import jp.springbook.springroosample.mydata.SampleData;
import jp.springbook.springroosample.mydata.SampleDataDataOnDemand;
import jp.springbook.springroosample.mydata.SampleDataIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SampleDataIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SampleDataIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SampleDataIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SampleDataIntegrationTest: @Transactional;
    
    @Autowired
    SampleDataDataOnDemand SampleDataIntegrationTest.dod;
    
    @Test
    public void SampleDataIntegrationTest.testCountSampleDatas() {
        Assert.assertNotNull("Data on demand for 'SampleData' failed to initialize correctly", dod.getRandomSampleData());
        long count = SampleData.countSampleDatas();
        Assert.assertTrue("Counter for 'SampleData' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SampleDataIntegrationTest.testFindSampleData() {
        SampleData obj = dod.getRandomSampleData();
        Assert.assertNotNull("Data on demand for 'SampleData' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SampleData' failed to provide an identifier", id);
        obj = SampleData.findSampleData(id);
        Assert.assertNotNull("Find method for 'SampleData' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SampleData' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SampleDataIntegrationTest.testFindAllSampleDatas() {
        Assert.assertNotNull("Data on demand for 'SampleData' failed to initialize correctly", dod.getRandomSampleData());
        long count = SampleData.countSampleDatas();
        Assert.assertTrue("Too expensive to perform a find all test for 'SampleData', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SampleData> result = SampleData.findAllSampleDatas();
        Assert.assertNotNull("Find all method for 'SampleData' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SampleData' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SampleDataIntegrationTest.testFindSampleDataEntries() {
        Assert.assertNotNull("Data on demand for 'SampleData' failed to initialize correctly", dod.getRandomSampleData());
        long count = SampleData.countSampleDatas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SampleData> result = SampleData.findSampleDataEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SampleData' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SampleData' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SampleDataIntegrationTest.testFlush() {
        SampleData obj = dod.getRandomSampleData();
        Assert.assertNotNull("Data on demand for 'SampleData' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SampleData' failed to provide an identifier", id);
        obj = SampleData.findSampleData(id);
        Assert.assertNotNull("Find method for 'SampleData' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySampleData(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'SampleData' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SampleDataIntegrationTest.testMergeUpdate() {
        SampleData obj = dod.getRandomSampleData();
        Assert.assertNotNull("Data on demand for 'SampleData' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SampleData' failed to provide an identifier", id);
        obj = SampleData.findSampleData(id);
        boolean modified =  dod.modifySampleData(obj);
        Integer currentVersion = obj.getVersion();
        SampleData merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SampleData' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SampleDataIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SampleData' failed to initialize correctly", dod.getRandomSampleData());
        SampleData obj = dod.getNewTransientSampleData(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SampleData' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SampleData' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SampleData' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SampleDataIntegrationTest.testRemove() {
        SampleData obj = dod.getRandomSampleData();
        Assert.assertNotNull("Data on demand for 'SampleData' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SampleData' failed to provide an identifier", id);
        obj = SampleData.findSampleData(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SampleData' with identifier '" + id + "'", SampleData.findSampleData(id));
    }
    
}
