// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package jp.springbook.springroosample.mydata;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import jp.springbook.springroosample.mydata.SampleData;
import jp.springbook.springroosample.mydata.SampleDataDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect SampleDataDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SampleDataDataOnDemand: @Component;
    
    private Random SampleDataDataOnDemand.rnd = new SecureRandom();
    
    private List<SampleData> SampleDataDataOnDemand.data;
    
    public SampleData SampleDataDataOnDemand.getNewTransientSampleData(int index) {
        SampleData obj = new SampleData();
        setAge(obj, index);
        setMail(obj, index);
        setMemo(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void SampleDataDataOnDemand.setAge(SampleData obj, int index) {
        Integer age = new Integer(index);
        obj.setAge(age);
    }
    
    public void SampleDataDataOnDemand.setMail(SampleData obj, int index) {
        String mail = "mail_" + index;
        obj.setMail(mail);
    }
    
    public void SampleDataDataOnDemand.setMemo(SampleData obj, int index) {
        String memo = "memo_" + index;
        obj.setMemo(memo);
    }
    
    public void SampleDataDataOnDemand.setName(SampleData obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public SampleData SampleDataDataOnDemand.getSpecificSampleData(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SampleData obj = data.get(index);
        Long id = obj.getId();
        return SampleData.findSampleData(id);
    }
    
    public SampleData SampleDataDataOnDemand.getRandomSampleData() {
        init();
        SampleData obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return SampleData.findSampleData(id);
    }
    
    public boolean SampleDataDataOnDemand.modifySampleData(SampleData obj) {
        return false;
    }
    
    public void SampleDataDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SampleData.findSampleDataEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SampleData' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SampleData>();
        for (int i = 0; i < 10; i++) {
            SampleData obj = getNewTransientSampleData(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
