// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package jp.springbook.springroosample.mydata;

import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import jp.springbook.springroosample.mydata.SampleData;

privileged aspect SampleData_Roo_Finder {
    
    public static TypedQuery<SampleData> SampleData.findSampleDatasByNameLike(String name) {
        if (name == null || name.length() == 0) throw new IllegalArgumentException("The name argument is required");
        name = name.replace('*', '%');
        if (name.charAt(0) != '%') {
            name = "%" + name;
        }
        if (name.charAt(name.length() - 1) != '%') {
            name = name + "%";
        }
        EntityManager em = SampleData.entityManager();
        TypedQuery<SampleData> q = em.createQuery("SELECT o FROM SampleData AS o WHERE LOWER(o.name) LIKE LOWER(:name)", SampleData.class);
        q.setParameter("name", name);
        return q;
    }
    
}
